package org.grapheneos.appupdateservergenerator.model

import com.android.apksig.ApkVerifier
import com.android.apksig.internal.util.AndroidSdkVersion
import org.grapheneos.appupdateservergenerator.apkparsing.AAPT2Invoker
import org.grapheneos.appupdateservergenerator.db.AppRelease
import org.grapheneos.appupdateservergenerator.util.digest
import java.io.File
import java.io.IOException
import java.security.cert.X509Certificate

/**
 * Encapsulates data from the [apkFile] that was taken from the [apkFile]'s manifest and signing
 * certificate info.
 */
data class AndroidApk(
    val apkFile: File,
    val label: String,
    val packageName: PackageName,
    val versionCode: VersionCode,
    val versionName: String,
    val minSdkVersion: Int,
    val certificates: List<X509Certificate>
) {
    fun toAppRelease(releaseTimestamp: UnixTimestamp, releaseNotes: String?) = AppRelease(
        packageName = packageName,
        versionName = versionName,
        versionCode = versionCode,
        minSdkVersion = minSdkVersion,
        releaseTimestamp = releaseTimestamp,
        sha256Checksum = apkFile.digest("SHA-256").toBase64String(),
        releaseNotes = releaseNotes
    )

    class Builder {
        var apkFile: File? = null
        var label: String? = null
        var packageName: PackageName? = null
        var versionCode: VersionCode? = null
        var versionName: String? = null
        var minSdkVersion: Int? = null
        var certificates: List<X509Certificate>? = null

        private val isBuildable: Boolean
            get() = apkFile != null &&
                    label != null &&
                    packageName != null &&
                    versionCode != null &&
                    versionName != null &&
                    minSdkVersion != null &&
                    certificates != null

        fun buildIfAllPresent(): AndroidApk? {
            return if (isBuildable) {
                AndroidApk(
                    apkFile = apkFile!!,
                    label = label!!,
                    packageName = packageName!!,
                    versionCode = versionCode!!,
                    versionName = versionName!!,
                    minSdkVersion = minSdkVersion!!,
                    certificates = certificates!!
                )
            } else {
                null
            }
        }

        /** Generated by IDEA */
        override fun toString(): String {
            return "Builder(apkFile=$apkFile, label=$label, packageName=$packageName, versionCode=$versionCode, " +
                    "versionName=$versionName, minSdkVersion=$minSdkVersion, certificates=$certificates)"
        }

    }

    companion object {
        val ascendingVersionCodeComparator = Comparator<AndroidApk> { a, b -> a.versionCode.compareTo(b.versionCode) }
        val descendingVersionCodeComparator: Comparator<AndroidApk> = ascendingVersionCodeComparator.reversed()
        /**
         * Builds an [AndroidApk] instance from the given [apkFile]. The [apkFile] will be stored as a member variable
         * in [AndroidApk.apkFile]. `apksigner verify` will be invoked on the APK to verify the signature of the APK.
         *
         * @throws IOException if an I/O error occurs, or the APK can't be parsed by the [aaptInvoker], or the APK
         * failed to verify with the [apkSignerInvoker]
         */
        fun verifyApkSignatureAndBuildFromApkFile(
            apkFile: File,
            aaptInvoker: AAPT2Invoker
        ): AndroidApk {
            val builder = Builder()
            builder.apkFile = apkFile
            aaptInvoker.getAndroidAppDetails(apkFile, builder)

            val verifyResult = ApkVerifier.Builder(apkFile)
                .setMinCheckedPlatformVersion(AndroidSdkVersion.R)
                .build()
                .verify()
            if (!verifyResult.isVerified) {
                throw IOException("APK signature verification failed: ${verifyResult.allErrors}")
            }

            builder.certificates = verifyResult.signerCertificates
            return builder.buildIfAllPresent() ?: throw IOException("failed to build: $builder")
        }
    }
}
